update cicd

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -77,19 +77,19 @@ jobs:
 
 
       - name: Wait for application to start
-        run: sleep 10
+        run: sleep 60
 
-      # - name: Verify deployment
-      #   run: |
-      #     if docker ps | grep -q triage_v2; then
-      #       echo "Container is running"
-      #     else
-      #       echo "Container failed to start"
-      #       docker logs triage_v2
-      #       exit 1
-      #     fi
+      - name: Verify deployment
+        run: |
+          if docker ps | grep -q triage_v2; then
+            echo "Container is running"
+          else
+            echo "Container failed to start"
+            docker logs triage_v2
+            exit 1
+          fi
 
-      #     curl -f http://localhost:8000 || exit 1
+          curl -f http://localhost:8000 || exit 1
 
       # - name: Verify deployment
       #   run: |
